### ISSUE TITLE
Updated format of NamespaceMetadata table

### ISSUE THREAD

**Issue by TonjaHeinemann** [umati/UA-for-MachineTools#23]
See Mail from Randy Armstrong to @TonjaHeinemann and @GoetzGoerisch on Jan 28, 2021:

The NodeSetValidator expects this table format

Attribute | Value
-- | --
BrowseName | http://opcfoundation.org/UA/<short name>/

Property | DataType | Value
--|--|--
NamespaceUri | String | http://opcfoundation.org/UA/<short name>
NamespaceVersion | String | X.YY
NamespacePublicationDate | DateTime | YYYY-MM-DD
IsNamespaceSubset | Boolean | True or False
StaticNodeIdTypes | IdType [] | {Numeric}
StaticNumericNodeIdRange | NumericRange [] | Null
StaticStringNodeIdPattern | String | Null
  |   |   |  

this needs to be addressed in future spec versions.

**Comment by GoetzGoerisch** [comment]
Fixed with v1.01.0
